### ISSUE TITLE
I'm wondering about snippet of code you have used

### ISSUE THREAD

**Issue by saadshahd** [sindresorhus/is-fn#1]
I'm wondering about your reasons of using this mechanism instead of the regular `typeof`, `instanceof`.
**_Just I want to learn from you**_, I've tried to search about differences my self but I got no thing.

**Comment by royling** [comment]
I got the same question. Though I've already read about [your thinking about one-line module](https://github.com/sindresorhus/ama/issues/10), I really did not understand why an npm module is required for this thing. IMHO, it's more simple to just put it as `typeof fn === 'function'` or something similar?

**Comment by saadshahd** [comment]
@RoyLING I'm not wondering about the one-line node module.

The question here why:
`toString.call(x) === '[object Function]'`
not:
`typeof x === 'function'`
nor:
`x instanceof Function`

**Comment by royling** [comment]
ok, got your point.

**Comment by sindresorhus** [comment]
This is what Lodash, Underscore and jQuery does. In modern environments `typeof` is good enough, but in older browsers (even Safari 8) and PhantomJS there are bugs and calling the internal `[[Class]]` directly `Object.prototype.toString.call()` works around that. I guess this is not useful in Node.js though, so I added a note https://github.com/sindresorhus/is-fn/commit/3d25982b0d57afa454eb238f749b9779735375c5.

You should not use `instanceof` though as it won't work if the function comes from another realm, e.g. another frame or window, in the browser.

Read more here: http://javascript.info/tutorial/type-detection

**Comment by daryl** [comment]
Interesting, thanks for clearing it up.

**Comment by saadshahd** [comment]
@sindresorhus Thanks, for clarifying the differences.
